### ISSUE TITLE
backend: connect to local sql database

### ISSUE THREAD

**Issue by ashydashysoflashy** [ashydashysoflashy/cpsc559-project#9]

**Comment by liza-khr** [comment]
#### 1. Gradle dependencies:
- `org.springframework.boot:spring-boot-starter-data-jpa` 
    - Simplifies interaction with DB so that we can access it using java objects instead of writing mySQL queries directly
- `mysql:mysql-connector-java`
    - JDBC driver, allows java apps to connect to mySQL databases

#### 2. Properties:
If using `application.properties`, something like:
```
spring.datasource.url=jdbc:mysql://<hostname:port>/<database name>
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.datasource.driver-class-name=com.mysql.jdbc.Driver // Might be 'com.mysql.cj.jdbc.Driver', conflicting sources
```
If using `application.yml`, something like:
```
spring:
  datasource:
    url: jdbc:mysql://<hostname:port>/<database name>
    username: <username>
    password: <password>
    driver-class-name: com.mysql.jdbc.Driver
```
#### 3. Create entity classes for each database table:

- `@Entity` class decorator to indicate it's a DB table
- Specify the columns as private fields. 
- `@Id` field decorator to indicate it's the primary key

Some examples here: https://spring.io/guides/gs/accessing-data-jpa
Repo will full example: https://github.com/spring-guides/gs-accessing-data-mysql/tree/main/complete
